// Generated by rstantools.  Do not edit by hand.

/*
    bmsma is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    bmsma is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with bmsma.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_bsma_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 28> locations_array__ =
  {" (found before start of program)",
  " (in 'bsma', line 7, column 2 to column 13)",
  " (in 'bsma', line 8, column 2 to column 11)",
  " (in 'bsma', line 9, column 2 to column 20)",
  " (in 'bsma', line 10, column 2 to column 25)",
  " (in 'bsma', line 11, column 2 to column 25)",
  " (in 'bsma', line 15, column 2 to column 11)",
  " (in 'bsma', line 16, column 2 to column 16)",
  " (in 'bsma', line 17, column 15 to column 20)",
  " (in 'bsma', line 17, column 2 to column 22)",
  " (in 'bsma', line 18, column 2 to column 20)",
  " (in 'bsma', line 19, column 2 to column 17)",
  " (in 'bsma', line 21, column 2 to column 18)",
  " (in 'bsma', line 22, column 2 to column 32)",
  " (in 'bsma', line 24, column 2 to column 26)",
  " (in 'bsma', line 25, column 2 to column 23)",
  " (in 'bsma', line 26, column 2 to column 21)",
  " (in 'bsma', line 27, column 2 to column 22)",
  " (in 'bsma', line 28, column 2 to column 19)",
  " (in 'bsma', line 30, column 2 to column 24)",
  " (in 'bsma', line 31, column 2 to column 24)",
  " (in 'bsma', line 34, column 4 to column 35)",
  " (in 'bsma', line 33, column 21 to line 35, column 3)",
  " (in 'bsma', line 33, column 2 to line 35, column 3)",
  " (in 'bsma', line 37, column 2 to column 59)",
  " (in 'bsma', line 3, column 2 to column 21)",
  " (in 'bsma', line 4, column 14 to column 19)",
  " (in 'bsma', line 4, column 2 to column 21)"};
#include <stan_meta_header.hpp>
class model_bsma final : public model_base_crtp<model_bsma> {
private:
  int n_obs;
  std::vector<Eigen::Matrix<double,-1,1>> x;
public:
  ~model_bsma() {}
  model_bsma(stan::io::var_context& context__, unsigned int
             random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_bsma_namespace::model_bsma";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 25;
      context__.validate_dims("data initialization", "n_obs", "int",
        std::vector<size_t>{});
      n_obs = std::numeric_limits<int>::min();
      current_statement__ = 25;
      n_obs = context__.vals_i("n_obs")[(1 - 1)];
      current_statement__ = 25;
      stan::math::check_greater_or_equal(function__, "n_obs", n_obs, 1);
      current_statement__ = 26;
      stan::math::validate_non_negative_index("x", "n_obs", n_obs);
      current_statement__ = 27;
      context__.validate_dims("data initialization", "x", "double",
        std::vector<size_t>{static_cast<size_t>(n_obs),
          static_cast<size_t>(2)});
      x = std::vector<Eigen::Matrix<double,-1,1>>(n_obs,
            Eigen::Matrix<double,-1,1>::Constant(2,
              std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> x_flat__;
        current_statement__ = 27;
        x_flat__ = context__.vals_r("x");
        current_statement__ = 27;
        pos__ = 1;
        current_statement__ = 27;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 27;
          for (int sym2__ = 1; sym2__ <= n_obs; ++sym2__) {
            current_statement__ = 27;
            stan::model::assign(x, x_flat__[(pos__ - 1)],
              "assigning variable x", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 27;
            pos__ = (pos__ + 1);
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1 + 1 + 1;
  }
  inline std::string model_name() const final {
    return "model_bsma";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_bsma_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ mu_x1 = DUMMY_VAR__;
      current_statement__ = 1;
      mu_x1 = in__.template read<local_scalar_t__>();
      local_scalar_t__ b_0 = DUMMY_VAR__;
      current_statement__ = 2;
      b_0 = in__.template read<local_scalar_t__>();
      local_scalar_t__ b_1 = DUMMY_VAR__;
      current_statement__ = 3;
      b_1 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      local_scalar_t__ sigma_u1 = DUMMY_VAR__;
      current_statement__ = 4;
      sigma_u1 = in__.template read_constrain_lb<local_scalar_t__,
                   jacobian__>(0, lp__);
      local_scalar_t__ sigma_u2 = DUMMY_VAR__;
      current_statement__ = 5;
      sigma_u2 = in__.template read_constrain_lb<local_scalar_t__,
                   jacobian__>(0, lp__);
      {
        local_scalar_t__ u_c = DUMMY_VAR__;
        Eigen::Matrix<local_scalar_t__,-1,-1> U =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(2, 2, DUMMY_VAR__);
        current_statement__ = 8;
        stan::math::validate_non_negative_index("uv", "n_obs", n_obs);
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> uv =
          std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(n_obs,
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(2, DUMMY_VAR__));
        Eigen::Matrix<local_scalar_t__,-1,1> sigma_u =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(2, DUMMY_VAR__);
        Eigen::Matrix<local_scalar_t__,-1,1> mu_x =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(2, DUMMY_VAR__);
        current_statement__ = 12;
        stan::model::assign(mu_x, mu_x1, "assigning variable mu_x",
          stan::model::index_uni(1));
        current_statement__ = 13;
        stan::model::assign(mu_x, (b_0 + (b_1 * mu_x1)),
          "assigning variable mu_x", stan::model::index_uni(2));
        current_statement__ = 14;
        u_c = ((1 / stan::math::sqrt(2)) / b_1);
        current_statement__ = 15;
        stan::model::assign(U, (stan::math::pow(b_1, 2) * u_c),
          "assigning variable U", stan::model::index_uni(1),
          stan::model::index_uni(1));
        current_statement__ = 16;
        stan::model::assign(U, (b_1 * u_c), "assigning variable U",
          stan::model::index_uni(1), stan::model::index_uni(2));
        current_statement__ = 17;
        stan::model::assign(U, (-b_1 * u_c), "assigning variable U",
          stan::model::index_uni(2), stan::model::index_uni(1));
        current_statement__ = 18;
        stan::model::assign(U, (1 * u_c), "assigning variable U",
          stan::model::index_uni(2), stan::model::index_uni(2));
        current_statement__ = 19;
        stan::model::assign(sigma_u, sigma_u1, "assigning variable sigma_u",
          stan::model::index_uni(1));
        current_statement__ = 20;
        stan::model::assign(sigma_u, sigma_u2, "assigning variable sigma_u",
          stan::model::index_uni(2));
        current_statement__ = 23;
        for (int j = 1; j <= n_obs; ++j) {
          current_statement__ = 21;
          stan::model::assign(uv,
            stan::math::multiply(U,
              stan::math::subtract(
                stan::math::log(
                  stan::model::rvalue(x, "x", stan::model::index_uni(j))),
                mu_x)), "assigning variable uv", stan::model::index_uni(j));
        }
        current_statement__ = 24;
        lp_accum__.add(stan::math::multi_normal_lpdf<propto__>(uv,
                         stan::math::rep_vector(0, 2),
                         stan::math::diag_matrix(sigma_u)));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_bsma_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double mu_x1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      mu_x1 = in__.template read<local_scalar_t__>();
      double b_0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      b_0 = in__.template read<local_scalar_t__>();
      double b_1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      b_1 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      double sigma_u1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      sigma_u1 = in__.template read_constrain_lb<local_scalar_t__,
                   jacobian__>(0, lp__);
      double sigma_u2 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      sigma_u2 = in__.template read_constrain_lb<local_scalar_t__,
                   jacobian__>(0, lp__);
      out__.write(mu_x1);
      out__.write(b_0);
      out__.write(b_1);
      out__.write(sigma_u1);
      out__.write(sigma_u2);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ mu_x1 = DUMMY_VAR__;
      current_statement__ = 1;
      mu_x1 = in__.read<local_scalar_t__>();
      out__.write(mu_x1);
      local_scalar_t__ b_0 = DUMMY_VAR__;
      current_statement__ = 2;
      b_0 = in__.read<local_scalar_t__>();
      out__.write(b_0);
      local_scalar_t__ b_1 = DUMMY_VAR__;
      current_statement__ = 3;
      b_1 = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, b_1);
      local_scalar_t__ sigma_u1 = DUMMY_VAR__;
      current_statement__ = 4;
      sigma_u1 = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_u1);
      local_scalar_t__ sigma_u2 = DUMMY_VAR__;
      current_statement__ = 5;
      sigma_u2 = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_u2);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "mu_x1", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "b_0", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "b_1", "double",
        std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "sigma_u1",
        "double", std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "sigma_u2",
        "double", std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ mu_x1 = DUMMY_VAR__;
      current_statement__ = 1;
      mu_x1 = context__.vals_r("mu_x1")[(1 - 1)];
      out__.write(mu_x1);
      local_scalar_t__ b_0 = DUMMY_VAR__;
      current_statement__ = 2;
      b_0 = context__.vals_r("b_0")[(1 - 1)];
      out__.write(b_0);
      local_scalar_t__ b_1 = DUMMY_VAR__;
      current_statement__ = 3;
      b_1 = context__.vals_r("b_1")[(1 - 1)];
      out__.write_free_lb(0, b_1);
      local_scalar_t__ sigma_u1 = DUMMY_VAR__;
      current_statement__ = 4;
      sigma_u1 = context__.vals_r("sigma_u1")[(1 - 1)];
      out__.write_free_lb(0, sigma_u1);
      local_scalar_t__ sigma_u2 = DUMMY_VAR__;
      current_statement__ = 5;
      sigma_u2 = context__.vals_r("sigma_u2")[(1 - 1)];
      out__.write_free_lb(0, sigma_u2);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"mu_x1", "b_0", "b_1", "sigma_u1",
                "sigma_u2"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "mu_x1");
    param_names__.emplace_back(std::string() + "b_0");
    param_names__.emplace_back(std::string() + "b_1");
    param_names__.emplace_back(std::string() + "sigma_u1");
    param_names__.emplace_back(std::string() + "sigma_u2");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "mu_x1");
    param_names__.emplace_back(std::string() + "b_0");
    param_names__.emplace_back(std::string() + "b_1");
    param_names__.emplace_back(std::string() + "sigma_u1");
    param_names__.emplace_back(std::string() + "sigma_u2");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu_x1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b_0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b_1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_u1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_u2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu_x1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b_0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b_1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_u1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_u2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((1 + 1) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((1 + 1) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_bsma_namespace::model_bsma;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_bsma_namespace::profiles__;
}
#endif
#endif
